### ISSUE TITLE
KeyError exception with Python SDK Code Example - "Wait for Confirmation"

### ISSUE THREAD

**Issue by tconnolly11** [algorand/py-algorand-sdk#234]
**Describe the error**
KeyError 'last-round' in [Wait For Confirmation](https://developer.algorand.org/docs/build-apps/hello_world/#wait-for-confirmation) Python example

**Link to the page or line**
Link to page: [https://developer.algorand.org/docs/build-apps/hello_world/#wait-for-confirmation](url)
Link to specific code: https://github.com/algorand/docs/blob/4686a0989976151752abc7f3fcdf22deaec15bb5/examples/start_building/v2/python/your_first_transaction.py#L21

**Supporting Info**
algod client I created following along with 'Start Building' tutorial:
```

from os import wait
from algosdk import algod, account, mnemonic
import json
from algosdk.future import transaction
from algosdk.future.transaction import PaymentTxn


algod_address = "http://localhost:4001"
algod_token = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
algod_client = algod.AlgodClient(algod_token, algod_address)
passphrase = "tornado mistake direct common away offer normal toe goose invite retire rack stable valve satisfy retire armed chair pioneer verb dice history sock able behave"

private_key = mnemonic.to_private_key(passphrase)
my_address = mnemonic.to_public_key(passphrase)
print("My address: {}".format(my_address))

account_info = algod_client.account_info(my_address)
print("Account balance: {} microAlgos".format(account_info.get('amount')))
"""
status = algod_client.status()
print(json.dumps(status, indent=4))
try:
    params = algod_client.suggested_params_as_object()
    print(json.dumps(vars(params), indent=4))
except Exception as e:
    print(e)
"""
params = algod_client.suggested_params_as_object()
params.flat_fee = True
params.fee = 10000
receiver = "GD64YIY3TWGDMCNPP553DZPPR6LDUSFQOIJVFDPPXWEG3FVOJCCDBBHU5A"
note = "Hello World this is my first txn".encode()

unsigned_txn = PaymentTxn(my_address, params, receiver, 1000000, None, note)

signed_txn = unsigned_txn.sign(mnemonic.to_private_key(passphrase))

txid = algod_client.send_transaction(signed_txn)
print("Succesfully sent transaction with txID: {}".format(txid))

# Utility for waiting on a transaction confirmation
def wait_for_confirmation(client, transaction_id, timeout):
    """
    Wait until the transaction is confirmed or rejected, or until 'timeout'
    number of rounds have passed.
    Args:
        transaction_id (str): the transaction to wait for
        timeout (int): maximum number of rounds to wait
    Returns:
        dict: pending transaction information, or throws an error if the transactions
            is not confirmed or rejected in the next timeout rounds
    """
    start_round = client.status()["last-round"] + 1;
    current_round = start_round

    while current_round < start_round + timeout:
        try:
            pending_txn = client.pending_transaction_info(transaction_id)
        except Exception:
            return
        if pending_txn.get("confirmed-round", 0) > 0:
            return pending_txn
        elif pending_txn["pool-error"]:
            raise Exception('pool error: {}'.format(pending_txn["pool-error"]))
        client.status_after_block(current_round)
        current_round += 1
    raise Exception('pending txn not found in timeout rounds, timeout value = : {}'.format(timeout))

wait_for_confirmation(algod_client, txid, 5)
```

Output of Error encountered:
```
algorand %  cd /Users/tc/Desktop/algorand ; /usr/bin/env /usr/local/bin/python3 /Users/tc/.vscode/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/debugpy/launcher 53173 -- /Users/tc/Desktop/algorand/algodclient.py 
My address: CZZVJXPCVFVEEA4FJ75QFL6Z4SXYWQHXKDXUBDGURPYCWGMHQAAJMTIBMM
Account balance: 22930000 microAlgos
Succesfully sent transaction with txID: RTUJU3JFWTADKW6VEMGQXFUMESO72DW36MOOKCSSWO6SFXTGBIWQ
Traceback (most recent call last):
  File "/Users/tc/Desktop/algorand/algodclient.py", line 69, in <module>
    wait_for_confirmation(algod_client, txid, 5)
  File "/Users/tc/Desktop/algorand/algodclient.py", line 53, in wait_for_confirmation
    start_round = client.status()["last-round"] + 1;
KeyError: 'last-round'
```

Verified /v2/status returns 'last-round':
```
sandbox % curl -i -X GET \
> -H "X-Algo-API-Token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" \
> 'http://localhost:4001/v2/status'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
Vary: Origin
Date: Wed, 01 Sep 2021 20:06:51 GMT
Content-Length: 580

{"catchpoint":"","catchpoint-acquired-blocks":0,"catchpoint-processed-accounts":0,"catchpoint-total-accounts":0,"catchpoint-total-blocks":0,"catchpoint-verified-accounts":0,"catchup-time":0,"last-catchpoint":"","last-round":16388542,"last-version":"https://github.com/algorandfoundation/specs/tree/abc54f79f9ad679d2d22f0fb9909fb005c16f8a1","next-version":"https://github.com/algorandfoundation/specs/tree/abc54f79f9ad679d2d22f0fb9909fb005c16f8a1","next-version-round":16388543,"next-version-supported":true,"stopped-at-unsupported-round":false,"time-since-last-round":3918509100}

**Comment by bbroder-uji** [comment]
tconnolly11 client code needs v2 imports
-from algosdk import algod, account, mnemonic
+from algosdk.v2client import algod
+from algosdk import account, mnemonic

-params = algod_client.suggested_params_as_object()
+params = algod_client.suggested_params()
