### ISSUE TITLE
Error in generate_account()

### ISSUE THREAD

**Issue by oggy95** [algorand/py-algorand-sdk#29]
Hi!
When I try to run the example code in "Quick start", I had an error in creating account:

```
python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from algosdk import account, encoding
>>> private_key, address = account.generate_account()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/algosdk/account.py", line 15, in generate_account
    a = encoding.encode_address(vk.encode())
  File "/usr/local/lib/python3.6/dist-packages/algosdk/encoding.py", line 134, in encode_address
    chksum = _checksum(addr_bytes)
  File "/usr/local/lib/python3.6/dist-packages/algosdk/encoding.py", line 149, in _checksum
    hash = hashes.Hash(hashes.SHA512_256(), default_backend())
AttributeError: module 'cryptography.hazmat.primitives.hashes' has no attribute 'SHA512_256'
```

OS: Ubuntu 18.04.3 LTS
py-algorand-sdk installed via pip3

**Comment by oggy95** [comment]
Figured out. It did not depend on the version of operation system.
Problems in the incorrect version of 'cryptography'. When installing py-algorand-sdk, it satisfied by version '1.2.3' of 'cryptography', but it causes the problem above. With version 2.8 it working correctly. Maybe in package should write requirements about a higher version of cryptography?
